# URL de conexi�n a PostgreSQL (con fallback a H2)
spring.datasource.url=${DB_URL:jdbc:h2:mem:testdb}

# Usuario y contrase�a
spring.datasource.username=${DB_USER_NAME:sa}
spring.datasource.password=${DB_PASSWORD:}

# Driver de PostgreSQL
spring.datasource.driver-class-name=${DB_DRIVER:org.h2.Driver}
# Dialecto de Hibernate
spring.jpa.database-platform=${DB_DIALECT:org.hibernate.dialect.H2Dialect}

# Configuraciones opcionales de JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# logs de debuggeo
#logging.level.org.springframework=DEBUG
#logging.level.org.hibernate=DEBUG
#logging.level.com.tu.paquete=DEBUG