# URL de conexi�n a PostgreSQL (con fallback a H2)
spring.datasource.url=${DB_URL}

# Usuario y contrase�a
spring.datasource.username=${DB_USER_NAME}
spring.datasource.password=${DB_PASSWORD}


# Configuraciones opcionales de JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# logs de debuggeo
#logging.level.org.springframework=DEBUG
#logging.level.org.hibernate=DEBUG
#logging.level.com.tu.paquete=DEBUG